name: Build CA55
run-name: Build CA55
on:
  workflow_call:
    inputs:
      TARGET_BOARD:
        description: Build target board
        type: string
        required: true
        default: "s4sk"
env:
  TARGET_BOARD: ${{ inputs.TARGET_BOARD  }}

jobs:
  Build:
    name: Build
    if: github.repository_owner == 'renesas-rcar'
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Aggressive cleanup
        # Based on https://github.com/NobuoTsukamoto/my_actions_test/blob/8f1ad38e225730322f196da7d958d0cfd49eca01/.github/workflows/test_contains.yml
        run: |
          df -h
          sudo rm -rf "/home/work/*" || true
          sudo rm -rf "/opt/*" || true
          sudo rm -rf "/usr/local/share/*" || true
          sudo rm -rf "/usr/share/dotnet" || true
          sudo rm -rf "$AGENT_TOOLSDIRECTORY" || true
          sudo rm -rf "/usr/local/lib/android" || true
          sudo rm -rf "/usr/lib/jvm" || true
          sudo rm -rf "/usr/share/swift" || true
          sudo rm -rf "/usr/local/julia*" || true
          sudo rm -rf "/usr/share/kotlinc" || true
          sudo rm -rf "/usr/share/miniconda" || true
          sudo rm -rf "/usr/share/sbt" || true
          sudo rm -rf "/usr/local/sqlpackage" || true
          sudo rm -rf "/usr/bin/yq" || true
          sudo rm -rf "/usr/local/bin/terraform" || true
          sudo rm -rf "/usr/local/bin/stack" || true
          sudo rm -rf "/usr/local/bin/aliyun" || true
          sudo rm -rf "/usr/local/bin/pulumi" || true
          sudo rm -rf "/usr/local/bin/pulumi-language-dotnet" || true
          sudo rm -rf "/usr/local/bin/azcopy" || true
          sudo rm -rf "/usr/local/aws-cli" || true
          sudo rm -rf "/usr/local/bin/bicep" || true
          sudo rm -rf "/usr/local/bin/rebar3" || true
          sudo rm -rf "/usr/local/bin/phpunit" || true
          sudo rm -rf "/usr/local/bin/packer" || true
          sudo rm -rf "/usr/local/bin/bicep" || true
          sudo rm -rf "/usr/local/bin/docker-compose" || true
          sudo rm -rf "/usr/local/bin/minikube" || true
          sudo rm -rf "/usr/local/bin/kustomize" || true
          sudo rm -rf "/usr/local/bin/kubectl" || true
          sudo rm -rf "/usr/local/bin/kind" || true
          sudo rm -rf "/usr/local/bin/helm" || true
          sudo rm -rf "/usr/local/bin/azcopy_11.3.1" || true
          sudo rm -rf "/usr/local/bin/bicep" || true
          sudo rm -rf "/usr/local/bin/.ghcup" || true
          sudo rm -rf "/usr/local/bin/phpunit" || true
          sudo rm -rf "/usr/local/bin/pulumi-*" || true
          sudo rm -rf "/usr/local/bin/oc" || true
          sudo rm -rf "/usr/local/bin/ctest" || true
          sudo rm -rf "/usr/local/bin/cmake-gui" || true
          sudo rm -rf "/usr/local/bin/ccmake" || true
          sudo rm -rf "/usr/local/bin/cpack" || true
          sudo rm -rf "/usr/local/bin/oras" || true
          sudo rm -rf "/home/.dotnet/tools" || true
          sudo rm -rf "/home/linuxbrew" || true
          sudo rm -rf "/home/.nvm" || true
          sudo rm -rf "/home/perflog" || true
          sudo rm -rf "/etc/skel/.dotnet/tools" || true
          sudo rm -rf "/usr/share/apache-maven-3.8.8" || true
          sudo rm -rf "/usr/share/gradle-8.7" || true
          sudo rm -rf "/usr/local/.ghcup" || true
          sudo rm -rf "/usr/bin/composer" || true
          sudo rm -rf "/usr/libexec/docker/cli-plugins" || true
          sudo rm -rf "/usr/bin/docker-credential-ecr-login" || true
          sudo rm -rf "/usr/local/lib/lein" || true
          sudo docker image prune --all --force
          sudo npm uninstall bazel || true
          sudo npm uninstall bazelisk || true
          rustup self uninstall -y
          ls -al /usr/local/share
          df -h
      - name: Remove more packages
        # Based on https://github.com/easimon/maximize-build-space/issues/30
        run: |
          removePackages=`apt list --manual-installed | awk '{print $1}' | sed 's|\(.*\)/.*|\1|' | grep -E -v 'base*|bash|binutils|bsdutils|bzip2|ca-certificates|coreutils|curl|dbus|diffutils|dpkg*|file|findutils|git*|grep|gzip|hostname|init|iproute2|iputils-ping|keyutils|lib*|linux-headers*|linux-image*|lld*|locales|login|lsb-release|make|net-tools|openssh-*|openssl|patchelf|rpm|rsync|session-manager-plugin|shellcheck|ssh|sudo|sysvinit-utils|tar|tcl*|time|tk|tzdata|ubuntu-*|unzip|upx-ucl|walinuxagent|wget|xz-utils|zip*|zsync|apt|dash|ncurses-bin|shim-signed|grub-efi-*|mokutil|sbsigntool|secureboot-db|docker-*|containerd.io' | tr '\n' ' '`
          echo "Removing following userinstalled packages: $removePackages"
          sudo apt-get update
          sudo apt-get purge -y $removePackages
          sudo dpkg -r packages-microsoft-prod > /dev/null 2>&1 || true
          sudo apt-get autoremove -y > /dev/null 2>&1 || true
          sudo apt-get autoclean -y > /dev/null 2>&1 || true
          df -h
      - name: Setup package
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential chrpath cpio debianutils diffstat file gawk gcc git iputils-ping \
            libacl1 liblz4-tool locales python3 python3-git python3-jinja2 python3-pexpect \
            python3-pip python3-subunit socat texinfo unzip wget xz-utils zstd device-tree-compiler
          sudo apt-get install -y \
            lvm2 parted
          # Clean up apt
          sudo apt autoremove -y
          sudo apt clean -y
          sudo apt autoclean -y
          df -h

      - name: Check disk and memory
        run: |
          df -h
          free -h

      - name: Mount addtional disk
        run: |
          sudo parted /dev/nvme0n1 --script mklabel gpt mkpart primary ext4 0% 100%
          sudo mkfs.ext4 /dev/nvme0n1p1
          sudo mkdir -p /mnt
          sudo mount /dev/nvme0n1p1 /mnt

      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 10240
          swap-size-mb: 8192

      - name: Check disk
        run: |
          df -h

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run build
        run: |
          cd tool
          ./setup_cr52.sh
          ./setup_ca55.sh
          cd ../application_cpu
          ./build_xenhypervisor.sh ${{ env.TARGET_BOARD }} -c
          ls -la deploy

      - name: Check disk
        run: |
          df -h

